### PR TITLE
Osm: fix crash on debug and way merge

### LINKED ISSUE #1115: Error in rtree when loading OpenStreetMap data
Error in rtree when loading OpenStreetMap data

Error from Debian stable, gcc version 4.9.2.
The error occur with file greater than very small file. Any where the pbf come from (geofabrik, mapzen, metro.teczno.com)

```
X:~/navitia/gtfs$ ../release/ed/osm2ed --connection-string "user=fred dbname=navitia password=123" --input paris.osm.pbf
NOTICE:  TRUNCATE cascade sur la table « edge »
NOTICE:  TRUNCATE cascade sur la table « rel_admin_admin »
NOTICE:  TRUNCATE cascade sur la table « rel_way_admin »
NOTICE:  TRUNCATE cascade sur la table « poi_properties »
[INFO] Reading the fileparis.osm.pbf
[INFO] We finished reading the file
[INFO] Reading the fileparis.osm.pbf
I don't know what to do with: foot=yes; designated
I don't know what to do with: bicycle=dismounted
[INFO] We finished reading the file
[INFO] Reading the fileparis.osm.pbf
[INFO] We finished reading the file
osm2ed: /home/fred/navitia/source/third_party/RTree/RTree.h:1390: void RTree<DATATYPE, ELEMTYPE, NUMDIMS, ELEMTYPEREAL, TMAXNODES, TMINNODES>::Classify(int, int, RTree<DATATYPE, ELEMTYPE, NUMDIMS, ELEMTYPEREAL, TMAXNODES, TMINNODES>::PartitionVars*) [with DATATYPE = const ed::connectors::OSMRelation*; ELEMTYPE = double; int NUMDIMS = 2; ELEMTYPEREAL = double; int TMAXNODES = 8; int TMINNODES = 4]: Assertion `PartitionVars::NOT_TAKEN == a_parVars->m_partition[a_index]' failed.
FATAL - We received signal: 6, so it's time to die!! version: v1.22.4-24-ga14338f
ERROR - ../release/ed/osm2ed(navitia::get_backtrace()+0x27) [0xd78a94]
../release/ed/osm2ed(navitia::print_backtrace()+0x9f) [0xd7d3cb]
../release/ed/osm2ed() [0xd6bc93]
/lib/x86_64-linux-gnu/libc.so.6(+0x35180) [0x7002059bc180]
/lib/x86_64-linux-gnu/libc.so.6(gsignal+0x37) [0x7002059bc107]
/lib/x86_64-linux-gnu/libc.so.6(abort+0x148) [0x7002059bd4e8]
/lib/x86_64-linux-gnu/libc.so.6(+0x2e226) [0x7002059b5226]
/lib/x86_64-linux-gnu/libc.so.6(+0x2e2d2) [0x7002059b52d2]
../release/ed/osm2ed(RTree<ed::connectors::OSMRelation const*, double, 2, double, 8, 4>::Classify(int, int, RTree<ed::connectors::OSMRelation const*, double, 2, double, 8, 4>::PartitionVars*)+0x62) [0xdadc24]
../release/ed/osm2ed(RTree<ed::connectors::OSMRelation const*, double, 2, double, 8, 4>::PickSeeds(RTree<ed::connectors::OSMRelation const*, double, 2, double, 8, 4>::PartitionVars*)+0x217) [0xdadbbf]
../release/ed/osm2ed(RTree<ed::connectors::OSMRelation const*, double, 2, double, 8, 4>::ChoosePartition(RTree<ed::connectors::OSMRelation const*, double, 2, double, 8, 4>::PartitionVars*, int)+0x99) [0xda7f27]
../release/ed/osm2ed(RTree<ed::connectors::OSMRelation const*, double, 2, double, 8, 4>::SplitNode(RTree<ed::connectors::OSMRelation const*, double, 2, double, 8, 4>::Node*, RTree<ed::connectors::OSMRelation const*, double, 2, double, 8, 4>::Branch const*, RTree<ed::connectors::OSMRelation const*, double, 2, double, 8, 4>::Node**)+0xb4) [0xda0552]
../release/ed/osm2ed(RTree<ed::connectors::OSMRelation const*, double, 2, double, 8, 4>::AddBranch(RTree<ed::connectors::OSMRelation const*, double, 2, double, 8, 4>::Branch const*, RTree<ed::connectors::OSMRelation const*, double, 2, double, 8, 4>::Node*, RTree<ed::connectors::OSMRelation const*, double, 2, double, 8, 4>::Node**)+0x102) [0xd92e5a]
../release/ed/osm2ed(RTree<ed::connectors::OSMRelation const*, double, 2, double, 8, 4>::InsertRectRec(RTree<ed::connectors::OSMRelation const*, double, 2, double, 8, 4>::Branch const&, RTree<ed::connectors::OSMRelation const*, double, 2, double, 8, 4>::Node*, RTree<ed::connectors::OSMRelation const*, double, 2, double, 8, 4>::Node**, int)+0x281) [0xd92c5d]
../release/ed/osm2ed(RTree<ed::connectors::OSMRelation const*, double, 2, double, 8, 4>::InsertRectRec(RTree<ed::connectors::OSMRelation const*, double, 2, double, 8, 4>::Branch const&, RTree<ed::connectors::OSMRelation const*, double, 2, double, 8, 4>::Node*, RTree<ed::connectors::OSMRelation const*, double, 2, double, 8, 4>::Node**, int)+0xd8) [0xd92ab4]
../release/ed/osm2ed(RTree<ed::connectors::OSMRelation const*, double, 2, double, 8, 4>::InsertRectRec(RTree<ed::connectors::OSMRelation const*, double, 2, double, 8, 4>::Branch const&, RTree<ed::connectors::OSMRelation const*, double, 2, double, 8, 4>::Node*, RTree<ed::connectors::OSMRelation const*, double, 2, double, 8, 4>::Node**, int)+0xd8) [0xd92ab4]
../release/ed/osm2ed(RTree<ed::connectors::OSMRelation const*, double, 2, double, 8, 4>::InsertRectRec(RTree<ed::connectors::OSMRelation const*, double, 2, double, 8, 4>::Branch const&, RTree<ed::connectors::OSMRelation const*, double, 2, double, 8, 4>::Node*, RTree<ed::connectors::OSMRelation const*, double, 2, double, 8, 4>::Node**, int)+0xd8) [0xd92ab4]
../release/ed/osm2ed(RTree<ed::connectors::OSMRelation const*, double, 2, double, 8, 4>::InsertRect(RTree<ed::connectors::OSMRelation const*, double, 2, double, 8, 4>::Branch const&, RTree<ed::connectors::OSMRelation const*, double, 2, double, 8, 4>::Node**, int)+0x86) [0xd889d8]
../release/ed/osm2ed(RTree<ed::connectors::OSMRelation const*, double, 2, double, 8, 4>::Insert(double const*, double const*, ed::connectors::OSMRelation const* const&)+0xa3) [0xd81cf7]
../release/ed/osm2ed(ed::connectors::OSMCache::build_relations_geometries()+0x17a) [0xd6de56]
../release/ed/osm2ed(main+0x4c7) [0xd77491]
/lib/x86_64-linux-gnu/libc.so.6(__libc_start_main+0xf5) [0x7002059a8b45]
../release/ed/osm2ed() [0xd6b96e]

Abandon
```

### PR DESCRIPTION
**Pull request by antoine-de**
- do not insert empty geometry in rtree
- merge way if they share the same city (we created separate way between the city's district)

Fix #1115 , thanks @frodrigo and @eturck for the bug report!

### CODE REVIEW

File: source/ed/osm2ed.cpp [hunk 1]
```diff
@@ -229,7 +236,7 @@ void OSMCache::match_nodes_admin() {
         if (!node.is_defined() || node.admin) {
             continue;
         }
-        node.admin = match_coord_admin(node.lon(), node.lat());
+        node.admin = match_coord_admin(node.lon(), node.lat(), 8);
```
Comment (pbougue) [inline source/ed/osm2ed.cpp]: add a comment on the level?

File: source/ed/osm2ed.cpp [hunk 2]
```diff
@@ -201,16 +202,22 @@ void OSMCache::build_relations_geometries() {
...
     const auto p = point(lon, lat);
+    typedef std::pair<uint32_t, std::vector<const OSMRelation*>*> level_relations;
 
-    std::vector<OSMRelation*> result;
-    auto callback = [](const OSMRelation* rel, void* vec)->bool{
-        reinterpret_cast<std::vector<const OSMRelation*>*>(vec)->push_back(rel);
+    std::vector<const OSMRelation*> result;
+    auto callback = [](const OSMRelation* rel, void* c)->bool{
+        level_relations* context;
+        context = reinterpret_cast<level_relations*>(c);
```
Comment (pbougue) [inline source/ed/osm2ed.cpp]: :sob:

**Comment by pbougue** [comment]
A "debug" PR without test is so sad... :cry:

File: source/ed/osm2ed.cpp (hunk 1 above)
Comment (pbougue) [inline source/ed/osm2ed.cpp]: make it a variable?

Comment (TeXitoi) [inline source/ed/osm2ed.cpp]: I prefer the 8 in match_coord_admin

Comment (pbougue) [inline source/ed/osm2ed.cpp]: I'm ok with that, not perfect but perfection is a bit expensive here

**Comment by antoine-de** [comment]
yep I hope you'll do something about it as soon as possible!

File: source/cities/cities.cpp [hunk 3]
```diff
@@ -135,29 +136,28 @@ void OSMCache::build_postal_codes(){
         if(relation.second.level != 9){
             continue;
         }
-        auto rel = this->match_coord_admin(relation.second.centre.get<0>(), relation.second.centre.get<1>(), 8);
+        auto rel = this->match_coord_admin(relation.second.centre.get<0>(), relation.second.centre.get<1>());
```
Comment (xlqian) [inline source/cities/cities.cpp]: ~~this~~, no?

File: source/cities/cities.cpp [hunk 4]
```diff
@@ -135,29 +136,28 @@ void OSMCache::build_postal_codes(){
...
         }
     }
 }
 
-OSMRelation* OSMCache::match_coord_admin(const double lon, const double lat, uint32_t level) {
+OSMRelation* OSMCache::match_coord_admin(const double lon, const double lat) {
     Rect search_rect(lon, lat);
     const auto p = point(lon, lat);
-    typedef std::pair<uint32_t, std::vector<OSMRelation*>*> level_relations;
+    typedef std::vector<OSMRelation*> relations;
```
Comment (xlqian) [inline source/cities/cities.cpp]: using

File: source/cities/cities.cpp [hunk 5]
```diff
@@ -135,29 +136,28 @@ void OSMCache::build_postal_codes(){
...
 
-    std::vector<OSMRelation*> result;
+    relations result;
     auto callback = [](OSMRelation* rel, void* c)->bool{
-        level_relations* context;
-        context = reinterpret_cast<level_relations*>(c);
-        if(rel->level == context->first){
-            context->second->push_back(rel);
+        relations* context;
+        context = reinterpret_cast<relations*>(c);
```
Comment (xlqian) [inline source/cities/cities.cpp]: relations\* context  = reinterpret_cast<relations*>(c); ?

File: source/cities/cities.cpp [hunk 6]
```diff
@@ -135,29 +136,28 @@ void OSMCache::build_postal_codes(){
...
+    typedef std::vector<OSMRelation*> relations;
 
-    std::vector<OSMRelation*> result;
+    relations result;
     auto callback = [](OSMRelation* rel, void* c)->bool{
-        level_relations* context;
-        context = reinterpret_cast<level_relations*>(c);
-        if(rel->level == context->first){
-            context->second->push_back(rel);
+        relations* context;
```
Comment (xlqian) [inline source/cities/cities.cpp]: this function never returns false, is that normal?

**Comment by TeXitoi** [comment]
OK for me.

**Comment by xlqian** [comment]
ok for me
