### PR TITLE
Doc: fix build script for ubuntu 16.04

### LINKED ISSUE #1872: build script fixes for ubuntu 16.04
postgresql ver. = 9.5
postgis ver. = 2.2

### PR DESCRIPTION
**Pull request by antoine-de**
close #1872 and #1871

the dataset link is ugly, but I don't see a better way to  do this

### CODE REVIEW

File: build_navitia.sh [hunk 1]
```diff
@@ -117,8 +117,10 @@ then
     echo "no gtfs or osm file given, we'll take a default data set, Paris"
 
     echo "getting gtfs paris data from data.navitia.io"
-    wget -P /tmp http://data.navitia.io/gtfs_paris_20140502.zip
-    unzip -d /tmp/gtfs /tmp/gtfs_paris_20140502.zip
+    # Note, here is a link to a dataset of the paris region. 
+    # You can explore https://navitia.opendatasoft.com if you want another dataset
+    wget -P /tmp https://navitia.opendatasoft.com/explore/dataset/fr-idf/files/dde578e47118b8c6f8885d75f18a504a/download/
+    unzip -d /tmp/gtfs /tmp/index.html
```
Comment (TeXitoi) [inline build_navitia.sh:123]: beautiful!

**Review by TeXitoi — APPROVED** [review]

File: build_navitia.sh (hunk 1 above)
Comment (antoine-de) [reply build_navitia.sh:123]: gnagnagna
